### PR TITLE
Add FlatObjectQueryBuilder

### PR DESCRIPTION
**Pull request by mingshl**
### Description
Add FlatObjectQueryBuilder and test file. To be updated after the FlatObjectFieldMapper works properly.

Overwritten some tests in FlatObjectFieldMapperTests.java to add to the TODO items, those needs to update accordingly to fit the cases of flat object. 

### Issues Resolved
#1018

### CODE REVIEW

**Comment by lukas-vlcek** [comment]
@mingshl 

I am adding some (formal) fixes:

`gradlew check` was complaining about the following:

- spotlessJavaCheck issues
- compilation errors for FlatObjectQueryBuilder

The first was fixed using `gradlew :plugins:flat-object:spotlessApply` task, the second by adding new ctors into `FlatObjectQueryBuilder` class.

Right now the `gradlew check` can be executed.

The first observation is that many `FlatObjectQueryBuilderTests` tests are failing because of something like:

```
Failed to parse mapping [_doc]: No handler for type [geo_shape] declared on field ...
```

Which seems like there is some default test functionality for `geo` inherited. Needs more investigation.

And then couple of tests for `FlatObjectFieldMapperTests` are failing due to:

```
Mapping definition for [field] has unsupported parameters:  [index : false] [doc_values : false] [store : true]
```

Again, something that needs to be investigated and fixed.

Overall, it seems we are on the right path.

**Review by lukas-vlcek — APPROVED** [review]
I added new commit on top of that. See my comments about it here https://github.com/mingshl/OpenSearch-Mingshl/pull/2#issuecomment-1412197492

I think we can merge and continue with investigation of test failures.
Also we shall consider rebasing on top of upstream `main` (so that we do not fall behind too much during time).

**Comment by mingshl** [comment]
Thanks @lukas-vlcek for applying the format. Merging the change. Will raise a new PR when there are more developments.

**Comment by lukas-vlcek** [comment]
@mingshl I think the [commit](https://github.com/mingshl/OpenSearch-Mingshl/commit/4bb5b34967c23e786dda5aa77e781aa8d3051228) that made it into the `flat-object` branch is missing [DCO](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) part.

**Comment by lukas-vlcek** [comment]
BTW, I figured out the issue with `FlatObjectFieldMapperTests` mentioned above (ie. `Mapping definition for [field] has unsupported parameters:  [index : false] [doc_values : false] [store : true]`).

The way to handle it correctly (and get rid of this issue) is to make `FlatObjectFieldMapper` inherit from `ParametrizedFieldMapper` and configure allowed parameters correctly (including internal filed Builder). I am working on that now...

**Comment by mingshl** [comment]
Thanks. Inherited the tests so the checks shall be enabled in the future commits.

**Pull request merged**
