### PR TITLE
Initial `flat-object` field feature commit

### PR DESCRIPTION
**Pull request by lukas-vlcek**
### Description

Initial boilerplate code for a new experimental plugin implementing #1018.

The code layout is following a typical plugin module; that means it contains all possible test categories (internal cluster, test, yaml) and the code structure was inspired by existing parent-join plugin.

This is WIP. As of now none of the tests is working correctly (throwing many java exceptions).

### Issues Resolved
 - #1018

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Lukáš Vlček <lukas.vlcek@aiven.io>

### CODE REVIEW

**Comment by mingshl** [comment]
Hi @lukas-vlcek Thanks for making the initial commit with plugin implementation. But considering in functionality wise, 'flat-object' is a very similar object type to 'keyword' and 'nested',  it can be implemented as API in 'server' package,  just like where 'keyword' is.  

One thing to consider is that there is a push to put an end to core plugins, opting to move things into separate repos where possible (and eventually extensions instead).

Also, core [https://github.com/opensearch-project/OpenSearch/tree/main/modules](module) are likely to stick around as a way to add functionality that sits outside of the core “server” package but is available by default.

So I would prefer implementing as feature within 'server' package than in a plugin.

**Comment by lukas-vlcek** [comment]
Thanks for looking at @mingshl 
I will move to code out of `plugins`, that should not be a problem.

**Comment by mingshl** [comment]
This is what I should do before you refactored: @nknize @dblock what are your thoughts to guide us about how to release this feature? 

My general idea for flat object will fall into this category: https://opensearch.org/docs/latest/opensearch/supported-field-types/object-fields/ Please correct me if I am wrong.

**Comment by mingshl** [comment]
merging this pull request to continue troubleshooting test failures, and further develop mapping field. Directed the release format question in the issue. Will open separate pull request to address the refactoring if needed.

**Pull request merged**
